apiVersion: v1
kind: Pod
metadata:
  name: debug-volume
  namespace: budeval
spec:
  containers:
  - name: debug
    image: busybox:1.35
    command: ["sleep", "600"]
    volumeMounts:
    - name: output
      mountPath: /workspace/outputs
  volumes:
  - name: output
    persistentVolumeClaim:
      claimName: 123e4567-e89b-12d3-a456-426614175007-output-pvc
  restartPolicy: Never
